# Base image
FROM gradle:6.9.0-jdk11
# Copy app files to container
COPY --chown=gradle:gradle . /CRD/

# Temp workaround to test locally
# COPY keys/* /usr/keys

# Set working directory so that all subsequent command runs in this folder
WORKDIR /CRD


RUN gradle build

# Download Stackdriver Profiler Java agent
RUN apt-get -y update && apt-get install -qqy \
    wget \
    && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /opt/cprof && \
    wget -q -O- https://storage.googleapis.com/cloud-profiler/java/latest/profiler_java_agent.tar.gz \
    | tar xzv -C /opt/cprof && \
    rm -rf profiler_java_agent.tar.gz

RUN GRPC_HEALTH_PROBE_VERSION=v0.4.11 && \
    wget -qO/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 && \
    chmod +x /bin/grpc_health_probe

# Expose port to access the app
EXPOSE 8090
# Command to run our app
CMD ./dockerRunnerDev.sh

