steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [
      'build',
      '-t',
      'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_TAG}',
      '-f',
      Dockerfile.dev,
      '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_TAG}']
images:
- 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_TAG}'

# Specify a default value for the _TAG substitution.
substitutions:
  _TAG: latest
  _SERVICE_NAME: dtr